export const FII_CATALOG = [
  ["MXRF11", "Maxi Renda"], ["HGLG11", "CSHG Logística"],
  ["KNRI11", "Kinea Renda Imobiliária"], ["XPLG11", "XP Logística"],
  ["VISC11", "Vinci Shopping Centers"], ["BCFF11", "BTG Fundo de Fundos"],
  ["XPML11", "XP Malls"], ["CPTS11", "Capitânia Securities II"],
  ["HGRU11", "CSHG Renda Urbana"], ["BTLG11", "BTG Pactual Logística"],
  ["VGHF11", "Valora Hedge Fund"], ["RBRF11", "RBR Alpha"],
  ["IRDM11", "Iridium Recebíveis"], ["KNSC11", "Kinea Securities"],
  ["MCCI11", "Mauá Capital Recebíveis"], ["HGCR11", "CSHG Recebíveis"],
  ["RECR11", "REC Recebíveis"], ["KNCR11", "Kinea Rendimentos"],
  ["XPCI11", "XP Crédito Imobiliário"], ["RBRR11", "RBR Rendimento High Grade"],
  ["TRXF11", "TRX Real Estate"], ["HGBS11", "Hedge Brasil Shopping"],
  ["HSML11", "HSI Malls"], ["GGRC11", "GGR Covepi"],
  ["LVBI11", "VBI Logístico"], ["BRCO11", "Bresco Logística"],
  ["DEVA11", "Devant Recebíveis"], ["URPR11", "Urca Prime Renda"],
  ["MALL11", "Malls Brasil Plural"], ["ALZR11", "Alianza Trust Renda"],
  ["JSRE11", "JS Real Estate"], ["PATL11", " Pátria Logística"],
  ["TGAR11", "TG Ativo Real"], ["RZTR11", "Riza Terrax"],
  ["VGIR11", "Valora CRI CDI"], ["BCRI11", "Banestes Recebíveis"],
] as const;
